# nginx proxy address - http://172.17.0.1:8102

name: speedtest
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: adolfintel/speedtest:latest
    pull_policy: always
    container_name: speedtest-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - speedtest
    ports:
      - "172.17.0.1:8102:80"
    environment:
      TZ: ${TZ:-America/New_York}
      TITLE: ${SPEEDTEST_TITLE:-LibreSpeed}
      TELEMETRY: false
    volumes:
      - ./volumes/data/speedtest:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  speedtest:
    name: speedtest
    external: false
